version: '3.8'

networks:
  my-network:
    driver: bridge
    
volumes:
  prometheus_data: {}

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    expose:
      - 3000
    links:
      - prometheus
    depends_on:
      - prometheus

  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    container_name: pihole-exporter
    environment:
      - INTERVAL=15s
      - PORT=9617
    ports:
      - 9617:9617
    expose:
      - 9617
    networks:
      - my-network
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    links:
      - pihole-exporter
    networks:
      - my-network
    depends_on:
      - pihole-exporter
